### PR TITLE
feat: adds link to each card

### PR DESCRIPTION
**Pull request by joe733**
Not sure if this is the right way to do it. Lemme know.. I'll change as per suggestions..

### CODE REVIEW

**Comment by joe733** [comment]
Hmm.. it works.. but that looks ugly.. I'll try fix some css..

**Comment by AbhayVAshokan** [comment]
The preview seems a little messed up. Have to edit the css as well. Why don't you fire it up locally and edit style.css file too?

**Comment by joe733** [comment]
I have not setup nettify.. gimme some time..

**Comment by AbhayVAshokan** [comment]
@joe733: Also, can you check if you got two pending pull requests on the Hacktoberfest site?

You don't need to setup netlify.

```zsh
git clone https://github.com/joe733/Hack-NASA-using-HTML.git
cd Hack-NASA-using-HTML
yarn install
yarn start
```

You'll have a live server on `https://localhost:8080`.

**Comment by joe733** [comment]
> @joe733: Also, can you check if you got two pending pull requests on the Hacktoberfest site?
> 
> You don't need to setup netlify.
> 
> ```shell
> git clone https://github.com/joe733/Hack-NASA-using-HTML.git
> cd Hack-NASA-using-HTML
> yarn install
> yarn start
> ```
> 
> You'll have a live server on `https://localhost:8080`.

Thanks!

Nope the hacktober page has not updated yet. Zero valid PRs so far.

**Comment by AbhayVAshokan** [comment]
Oh, I thought it was instantaneous. Perhaps check after some time and let me know if you got two.

**Comment by joe733** [comment]
Hey, fixed it. And yes there are 2 PRs from this repo on hactoberfest.

**Comment by AbhayVAshokan** [comment]
I've made some small changes.
1. Moved card padding to <a /> instead. Earlier the card padding region was not clickable.
2. Resolved merge conflicts.

**Review by AbhayVAshokan — APPROVED** [review]

**Comment by joe733** [comment]
okay 👍🏻  looks good to me

**Pull request merged**
